# Generated by Django 5.0.3 on 2024-04-04 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userCongreso', '0004_remove_servicio_usuarioasignado'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='categoria',
            field=models.CharField(default='abierto', max_length=15),
        ),
        migrations.AddField(
            model_name='servicio',
            name='problema',
            field=models.CharField(default='', max_length=25),
        ),
    ]
