# Generated by Django 5.0.3 on 2024-04-05 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userCongreso', '0005_servicio_categoria_servicio_problema'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaNivel1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='area_responsable1', to='userCongreso.usuario')),
            ],
        ),
        migrations.AlterField(
            model_name='servicio',
            name='areaSolicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userCongreso.areanivel1'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userCongreso.areanivel1'),
        ),
        migrations.CreateModel(
            name='AreaNivel2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('area_nivel1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userCongreso.areanivel1')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='area_responsable2', to='userCongreso.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='AreaNivel3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('area_nivel2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userCongreso.areanivel2')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='area_responsable3', to='userCongreso.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='AreaNivel4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('area_nivel3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userCongreso.areanivel3')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='area_responsable4', to='userCongreso.usuario')),
            ],
        ),
        migrations.DeleteModel(
            name='Area',
        ),
    ]
