# Generated by Django 5.0.3 on 2024-04-08 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userCongreso', '0006_areanivel1_alter_servicio_areasolicitante_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='areanivel1',
            name='responsable',
        ),
        migrations.RemoveField(
            model_name='areanivel3',
            name='area_nivel2',
        ),
        migrations.RemoveField(
            model_name='areanivel3',
            name='responsable',
        ),
        migrations.RemoveField(
            model_name='areanivel4',
            name='area_nivel3',
        ),
        migrations.RemoveField(
            model_name='areanivel4',
            name='responsable',
        ),
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('subareas', models.BooleanField()),
                ('levelarea', models.IntegerField()),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='area_responsable1', to='userCongreso.usuario')),
            ],
        ),
        migrations.AlterField(
            model_name='servicio',
            name='areaSolicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userCongreso.areas'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userCongreso.areas'),
        ),
        migrations.DeleteModel(
            name='AreaNivel2',
        ),
        migrations.DeleteModel(
            name='AreaNivel3',
        ),
        migrations.DeleteModel(
            name='AreaNivel4',
        ),
        migrations.DeleteModel(
            name='AreaNivel1',
        ),
    ]
