# Generated by Django 5.0.3 on 2024-04-08 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userCongreso', '0007_remove_areanivel1_responsable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('responsable', models.CharField(blank=True, max_length=100, null=True)),
                ('parent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userCongreso.area')),
            ],
        ),
        migrations.AlterField(
            model_name='servicio',
            name='areaSolicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userCongreso.area'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userCongreso.area'),
        ),
        migrations.DeleteModel(
            name='Areas',
        ),
    ]
