# Generated by Django 5.0.3 on 2024-04-08 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userCongreso', '0008_area_alter_servicio_areasolicitante_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='parent_id',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='area',
        ),
        migrations.AddField(
            model_name='usuario',
            name='es_responsable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='area',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='area',
            name='responsable',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userCongreso.usuario'),
        ),
    ]
