# Generated by Django 5.0.3 on 2024-04-08 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userCongreso', '0010_usuario_pertenece'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='responsable',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='es_responsable',
        ),
    ]
