# Generated by Django 5.0.3 on 2024-04-10 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userCongreso', '0011_remove_area_responsable_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='categoria',
        ),
    ]
