# Generated by Django 5.0.3 on 2024-04-10 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userCongreso', '0012_remove_servicio_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='folio',
            field=models.CharField(default=0, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='descripcion',
            field=models.TextField(max_length=300),
        ),
    ]
