# Generated by Django 5.0.3 on 2024-04-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userCongreso', '0013_servicio_folio_alter_servicio_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='nombreSolicitante',
            field=models.CharField(max_length=100),
        ),
    ]
