# Generated by Django 5.0.3 on 2024-04-16 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userCongreso', '0014_alter_servicio_nombresolicitante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='fechaCierre',
            field=models.DateTimeField(null=True),
        ),
    ]
