# Generated by Django 5.0.3 on 2024-04-16 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userCongreso', '0016_problemas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Problemas',
            new_name='Problema',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='problema',
        ),
    ]
