# Generated by Django 5.0.3 on 2024-04-18 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userCongreso', '0018_servicio_problema'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='comentarios',
            field=models.TextField(default='sin comentar', max_length=350),
        ),
    ]
