# Generated by Django 5.0.3 on 2024-04-30 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userCongreso', '0019_servicio_comentarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problema',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
