# Generated by Django 5.1.1 on 2024-09-16 23:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Problemas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(default=0, max_length=20, unique=True)),
                ('nombreSolicitante', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=300)),
                ('estado', models.CharField(default='abierto', max_length=15)),
                ('fechaCreacion', models.DateTimeField()),
                ('comentarios', models.TextField(default='sin comentar', max_length=350)),
                ('fechaCierre', models.DateTimeField(null=True)),
                ('areaSolicitante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarioFEI.area')),
                ('problema', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarioFEI.problemas')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_responsable', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
