# Generated by Django 5.1.1 on 2024-09-22 00:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarioFEI', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='estado',
            field=models.CharField(choices=[('solicitado', 'Solicitado'), ('asignado', 'Asignado'), ('en_atencion', 'En Atención'), ('finalizado', 'Finalizado')], default='solicitado', max_length=15),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='fechaCierre',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='fechaCreacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='folio',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_responsable', to=settings.AUTH_USER_MODEL),
        ),
    ]
