# Generated by Django 5.1.1 on 2024-09-27 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_rol_alter_usuariocc_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='nombre',
            field=models.CharField(default='sin asignar', max_length=30),
        ),
    ]
