# Generated by Django 5.1.1 on 2024-10-11 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_alter_usuariocc_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariocc',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
