# Generated by Django 5.0.3 on 2024-04-03 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_area_areati'),
    ]

    operations = [
        migrations.AddField(
            model_name='userti',
            name='cargaTrabajo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userti',
            name='disponibilidad',
            field=models.CharField(default='disponible', max_length=20),
        ),
    ]
