# Generated by Django 5.0.3 on 2024-04-04 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userti_cargatrabajo_userti_disponibilidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userti',
            name='area',
            field=models.CharField(default='No especificada', max_length=25),
        ),
        migrations.AlterField(
            model_name='userti',
            name='rol',
            field=models.CharField(default='No especificado', max_length=14),
        ),
        migrations.DeleteModel(
            name='AreaTI',
        ),
    ]
