# Generated by Django 5.0.3 on 2024-04-04 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_userti_area_alter_userti_rol_delete_areati'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userti',
            name='area',
            field=models.CharField(default='No especificada', max_length=30),
        ),
    ]
